### ISSUE TITLE
Unable to install module:  ParseError: "External ID not found in the system: etl.action_etl_action_actions" while parsing /opt/odoo/custom/etl/view/manager_view.xml:27, near <record id="view_etl_manager_form" model="ir.ui.view">

### ISSUE THREAD

**Issue by provaleks** [ingadhoc/odoo-etl#4]
I'm trying to install the odoo-etl (v8 branch) module on Odoo v8 server.

I've copied the "etl" folder into custom module-directory, restartet Odoo, created a new db, updated modules list. I find odoo-etl module in the list and press install. (Is this the wrong way to install the module?)

The following error comes up:

```
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 757, in _tag_record
    f_val = _eval_xml(self,field, self.pool, cr, self.uid, self.idref)
  File "/opt/odoo/openerp/tools/convert.py", line 177, in _eval_xml
    for n in node]), idref)
  File "/opt/odoo/openerp/tools/convert.py", line 166, in _process
    idref[id] = self.id_get(cr, id)
  File "/opt/odoo/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/odoo/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 932, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/odoo/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 922, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: etl.action_etl_action_actions" while parsing /opt/odoo/custom/etl/view/manager_view.xml:27, near
<record id="view_etl_manager_form" model="ir.ui.view">
            <field name="name">etl.manager.form</field>
            <field name="model">etl.manager</field>
            <field name="arch" type="xml">
                <form string="manager">
                    <header>
                        <button name="read_and_get" string="Read and get Records" class="oe_highlight" type="object"/>
                        <button name="read_models" string="Read Models" type="object"/>
                        <!-- <button name="order_source_models" string="Order Source Models" type="object"/> -->
                        <button name="get_records" string="Get Records Number" type="object"/>
                        <button name="match_models_and_order_actions" string="Match and Order" class="oe_highlight" type="object"/>
                        <button name="match_models" string="Match Models" type="object"/>
                        <button name="order_actions" string="Order Actions" type="object"/>
                        <button name="run_actions" string="Run Actions" class="oe_highlight" type="object"/>
                        <button name="read_active_source_models" string="Read Active Source Models" class="oe_highlight" type="object"/>
                        <button name="run_repeated_actions" string="Run Repeating Actions" class="oe_highlight" type="object"/>
                        <button name="delete_workflows" string="Delete Workflows" class="oe_highlight" type="object"/>
                        <!-- <button name="update_workflows" string="Update Workflows" class="oe_highlight" type="object"/> -->
                    </header>
                    <sheet string="Manager">
                        <div class="oe_right oe_button_box" name="buttons">
                            <button class="oe_inline" type="action" string="Actions" name="%(etl.action_etl_action_actions)d" context="{'search_default_manager_id': active_id}"/>
                            <button class="oe_inline" type="action" string="Value Mapping Fields" name="%(etl.action_etl_value_mapping_field_value_mapping_fields)d" context="{'search_default_manager_id': active_id}"/>
                        </div>
                        <group>
                            <field name="name"/>
                        </group>
                        <group col="6">
                            <field name="source_hostname"/>
                            <field name="source_port"/>
                            <field name="source_database"/>
                            <field name="source_login"/>
                            <field name="source_password" password="True"/>
                            <newline/>
                            <field name="target_hostname"/>
                            <field name="target_port"/>
                            <field name="target_database"/>
                            <field name="target_login"/>
                            <field name="target_password" password="True"/>
                            <newline/>
                        </group>
                        <group>
                            <field name="workflow_models"/>
                        </group>
                        <notebook>
                            <page string="Actions">
                                <group col="1">
                                    <field name="repeating_models"/>
                                    <field name="action_ids" context="{'from_manager':True}"/>
                                </group>
                            </page>
                            <page string="Exceptions">
                                <group col="1">
                                    <field name="model_exception_words"/>
                                    <field name="model_disable_default"/>
                                    <field name="model_analyze_default"/>
                                    <field name="field_disable_default"/>
                                    <field name="field_analyze_default"/>
                                    <field name="field_disable_words"/>
                                </group>
                            </page>
                            <page string="Log">
                                <field name="log"/>
                            </page>
                            <page string="notes">
                                <button name="install_modules" string="Install Modules" class="oe_highlight" type="object"/>
                                <group>
                                    <field name="modules_to_install"/>
                                </group>
                                <field name="note"/>
                            </page>
                            <page string="Value Mapping Fields">
                                <field name="value_mapping_field_ids" context="{'default_manager_id':id}"/>
                            </page>
                            <page string="External Models">
                                <field name="external_model_ids"/>
                            </page>
                        </notebook>
                    </sheet>

                </form>
            </field>
        </record>
```

**Comment by jjscarafia** [comment]
Please, wait me one week, I'm still working in this migration and some
minor improovements.
But if you want, try pulling again, I've push some changes.
Regards!

**Comment by jjscarafia** [comment]
Solved

**Comment by nishad12345** [comment]
External ID not found in the system: purchase.route_warehouse0_buy
this my database show the error 
 sir ,can you help me

**Comment by nishad12345** [comment]
i want create new product this show the massege how i can create the product

**Comment by nishad12345** [comment]
Traceback (most recent call last):
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/10.0/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/10.0/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/models.py", line 1121, in default_get
    defaults.update(self.env[model].default_get(names))
  File "/home/odoo/src/odoo/10.0/odoo/models.py", line 1108, in default_get
    defaults[name] = field.default(self)
  File "/home/odoo/src/odoo/10.0/addons/purchase/models/purchase.py", line 1053, in <lambda>
    route_ids = fields.Many2many(default=lambda self: self._get_buy_route())
  File "/home/odoo/src/odoo/10.0/addons/purchase/models/purchase.py", line 1032, in _get_buy_route
    buy_route = self.env.ref('purchase.route_warehouse0_buy')
  File "/home/odoo/src/odoo/10.0/odoo/api.py", line 785, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_model.py", line 1043, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_model.py", line 1027, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/home/odoo/src/odoo/10.0/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/ir/ir_model.py", line 1016, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: purchase.route_warehouse0_buy

**Comment by nishad12345** [comment]
Sir solve  this my problem

**Comment by lei314121077** [comment]
Please  sir plases solve this my problem

**Comment by jjscarafia** [comment]
Hi, we are not supporting this project any more. I've upload a few modifications on branch 9.0 (that should works on 8.0 also) proposed by infinity solutions. We haven't try them and we are not going to work on this for now. So, please, if you have an error please try to solve it and propose a PR. 
Thanks,
Juan
